### ISSUE TITLE
lumen 5.4

### ISSUE THREAD

**Issue by zongmi** [mpociot/laravel-test-factory-helper#20] opened 2017-08-10 03:12 UTC
The JSON field type that does not seem to support mysql5.7

Exception: Unknown database type json requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.

Mongodb doesn't seem to support either

Exception: call_user_func_array() expects parameter 1 to be a valid callback, class 'MongoDB\Database' does not have a method 'getDoctrineDriver'

**Comment by jrmadsen67** [comment] 2018-12-24 02:49
this is a duplicate of #11 

#close

**Closed** 2019-06-23 14:18 UTC
